name: Run Evaluation Engine

on:
  push:
    branches: ["*"]  # 全ブランチで実行

jobs:
  run-evaluation-engine:
    runs-on: self-hosted
    
    steps:
    - name: Checkout drowsy_detection code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 全履歴を取得
    
    - name: Verify Python installation
      shell: cmd
      run: |
        echo ========================================
        echo Python環境の詳細確認
        echo ========================================
        echo Python環境の確認中...
        python --version
        python -c "import sys; print(f'Python {sys.version}')"
        python -c "import sys; print(f'Python実行パス: {sys.executable}')"
        python -c "import sys; print(f'Pythonパス: {sys.path}')"
        echo 現在のディレクトリ:
        cd
        echo 環境変数PATH:
        echo %PATH%
        echo ✅ Python環境OK
    
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true  # セルフホストではキャッシュが残るため有効化
        version: latest     # 最新版のuvを指定（必要に応じて特定バージョンを指定可能）

    - name: Verify uv installation
      shell: cmd
      run: |
        echo ========================================
        echo uvの詳細確認
        echo ========================================
        echo uvの確認中...
        where uv
        uv --version
        echo ✅ uv準備完了
    
    - name: Clone evaluation_engine repository
      shell: cmd
      run: |
        echo ========================================
        echo evaluation_engineリポジトリのクローン
        echo ========================================
        echo evaluation_engineリポジトリをクローン中...
        echo 現在のディレクトリ:
        cd
        echo ディレクトリ内容:
        dir
        if exist evaluation_engine (
          echo 既存のディレクトリを削除中...
          rmdir /s /q evaluation_engine
        )
        echo Gitクローン実行:
        git clone https://github.com/abekoki/evaluation_engine.git
        echo クローン後のディレクトリ内容:
        dir
        cd evaluation_engine
        echo evaluation_engineディレクトリ内容:
        dir
        echo ✅ evaluation_engineクローン完了
    
    - name: Setup evaluation_engine environment
      shell: cmd
      run: |
        echo ========================================
        echo evaluation_engine環境セットアップ
        echo ========================================
        cd evaluation_engine
        echo evaluation_engineディレクトリに移動完了
        echo 現在のディレクトリ:
        cd
        echo evaluation_engineディレクトリ内容:
        dir
        
        echo ========================================
        echo uv syncで依存関係を解決
        echo ========================================
        echo uv syncを実行中...
        uv sync
        if errorlevel 1 (
          echo ❌ uv syncに失敗しました
          exit /b 1
        )
        echo ✅ uv sync完了
        echo ✅ evaluation_engine環境セットアップ完了
    
    - name: Run evaluation_engine main.py
      shell: cmd
      run: |
        echo ========================================
        echo evaluation_engine main.py実行
        echo ========================================
        cd evaluation_engine
        echo evaluation_engineディレクトリに移動完了
        echo 現在のディレクトリ:
        cd
        echo evaluation_engineディレクトリ内容:
        dir
        echo main.pyファイルの確認:
        dir main.py
        
        echo uv run main.pyを実行中...
        uv run main.py
        if errorlevel 1 (
          echo ❌ uv run main.pyに失敗しました
          echo エラー詳細を確認:
          echo 仮想環境内のPythonパス:
          call .venv\Scripts\activate.bat && python -c "import sys; print(sys.executable)"
          echo 仮想環境内のパッケージ一覧:
          call .venv\Scripts\activate.bat && python -m pip list
          exit /b 1
        )
        echo ✅ evaluation_engine実行完了
    
    - name: Upload evaluation results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: evaluation-results-${{ github.sha }}
        path: evaluation_engine/
        retention-days: 30