name: Run Evaluation Engine

on:
  push:
    branches: [ "*" ]  # 全ブランチで実行

jobs:
  run-evaluation-engine:
    runs-on: self-hosted
    
    steps:
    - name: Checkout drowsy_detection code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 全履歴を取得
    
    - name: Verify Python installation
      shell: cmd
      run: |
        echo Python環境の確認中...
        python --version
        python -c "import sys; print(f'Python {sys.version}')"
        echo ✅ Python環境OK
    
    - name: Install uv (if not available)
      shell: cmd
      run: |
        echo uvの確認中...
        where uv >nul 2>&1 || (
          echo uvをシステム全体にインストール中...
          python -m pip install --user uv
          echo uvのパスを確認中...
          python -c "import shutil; print(shutil.which('uv') or 'uv not found in PATH')"
        )
        echo uvのパス確認:
        where uv 2>nul || echo uvがパスに見つかりません
        echo ✅ uv準備完了
    
    - name: Clone evaluation_engine repository
      shell: cmd
      run: |
        echo evaluation_engineリポジトリをクローン中...
        if exist evaluation_engine (
          echo 既存のディレクトリを削除中...
          rmdir /s /q evaluation_engine
        )
        git clone https://github.com/abekoki/evaluation_engine.git
        cd evaluation_engine
        echo ✅ evaluation_engineクローン完了
    
    - name: Setup evaluation_engine environment
      shell: cmd
      run: |
        cd evaluation_engine
        echo evaluation_engineの環境セットアップ中...
        
        REM 仮想環境の作成
        echo 仮想環境作成中...
        where uv >nul 2>&1 && (
          echo uvコマンドを使用して仮想環境作成
          uv venv
        ) || (
          echo uvが見つからないため、python -m venvを使用
          python -m venv .venv
        )
        if errorlevel 1 (
          echo ❌ 仮想環境作成に失敗しました
          exit /b 1
        )
        echo ✅ 仮想環境作成完了
        
        REM 依存関係のインストール
        echo 依存関係インストール中...
        call .venv\Scripts\activate.bat
        if errorlevel 1 (
          echo ❌ 仮想環境のアクティベートに失敗しました
          exit /b 1
        )
        where uv >nul 2>&1 && (
          echo uvコマンドを使用して依存関係インストール
          uv sync
        ) || (
          echo uvが見つからないため、pipを使用
          pip install -r requirements.txt 2>nul || echo requirements.txtが見つかりません
        )
        if errorlevel 1 (
          echo ❌ 依存関係のインストールに失敗しました
          exit /b 1
        )
        echo ✅ 依存関係インストール完了
        
        REM drowsy_detectionアルゴリズムのインストール
        echo drowsy_detectionインストール中...
        where uv >nul 2>&1 && (
          echo uvコマンドを使用してdrowsy_detectionインストール
          uv pip install -e ../
        ) || (
          echo pipを使用してdrowsy_detectionインストール
          pip install -e ../
        )
        if errorlevel 1 (
          echo ❌ drowsy_detectionのインストールに失敗しました
          exit /b 1
        )
        echo ✅ drowsy_detectionインストール完了
        
        echo ✅ evaluation_engine環境セットアップ完了
    
    - name: Run evaluation_engine main.py
      shell: cmd
      run: |
        cd evaluation_engine
        echo evaluation_engineのmain.pyを実行中...
        call .venv\Scripts\activate.bat
        if errorlevel 1 (
          echo ❌ 仮想環境のアクティベートに失敗しました
          exit /b 1
        )
        python main.py
        if errorlevel 1 (
          echo ❌ main.pyの実行に失敗しました
          exit /b 1
        )
        echo ✅ evaluation_engine実行完了
    
    - name: Upload evaluation results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: evaluation-results-${{ github.sha }}
        path: evaluation_engine/
        retention-days: 30
